### ISSUE TITLE
Program crash on login.

### ISSUE THREAD

**Issue by MrBabalafe** [MrBabalafe/Inventory-Program#1]
When you create a User (ex. username Bob, password 123) and attempt to sign in with the incorrect username but correct password the program crashes. (Ex. username Jim, password 123)

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at PasswordManager.checkPassword(PasswordManager.java:32)
        at Main.main(Main.java:36)

The issue is inside of the findUserIndex() method in PasswordManager.java

**Comment by MrBabalafe** [comment]
Issue Fixed
